/* eslint-disable camelcase */
export const AddressMapping: any = {
  properties: {
    place_id: { type: 'long' },
    parent_place_id: { type: 'long' },
    osm_type: { type: 'keyword' },
    osm_id: { type: 'long' },
    category: { type: 'keyword' },
    type: { type: 'keyword' },
    admin_level: { type: 'long' },
    localname: { type: 'keyword' },
    housenumber: { type: 'keyword' },
    country_code: { type: 'keyword' },
    indexed_date: { type: 'keyword' },
    importance: { type: 'float' },
    extratags: { type: 'object', dynamic: 'false' },
    names: { type: 'object', dynamic: 'false' },
    calculated_importance: { type: 'float' },
    calculated_wikipedia: { type: 'keyword' },
    icon: { type: 'keyword' },
    rank_address: { type: 'long' },
    rank_search: { type: 'long' },
    isarea: { type: 'boolean' },
    centroid: { type: 'geo_point' },
    geometry: {
      type: 'geo_shape',
    },
    address: {
      type: 'nested',
      properties: {
        localname: { type: 'keyword' },
        place_id: { type: 'long' },
        osm_id: { type: 'long' },
        osm_type: { type: 'keyword' },
        place_type: { type: 'keyword' },
        class: { type: 'keyword' },
        type: { type: 'keyword' },
        admin_level: { type: 'long' },
        rank_address: { type: 'long' },
        distance: { type: 'float' },
        isaddress: { type: 'boolean' },
      },
    },
    linked_places: {
      type: 'nested',
      properties: {
        localname: { type: 'keyword' },
        place_id: { type: 'long' },
        osm_id: { type: 'long' },
        osm_type: { type: 'keyword' },
        place_type: { type: 'keyword' },
        class: { type: 'keyword' },
        type: { type: 'keyword' },
        admin_level: { type: 'long' },
        rank_address: { type: 'long' },
        distance: { type: 'float' },
        isaddress: { type: 'boolean' },
      },
    },
  },
};
